name: Continuous Integration e Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0


  telegram:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Send Telegram alert on failure
      if: failure()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="🚨 Atenção: A build do projeto ${{ github.repository }} falhou no commit ${{ github.sha }}. Veja detalhes em: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Pull Request Telegram
      uses: F2had/pr-telegram-action@v1.0.0
      with: 
        bot_token: '${{ secrets.BotToken }}' 
        chat_id: '${{ secrets.CHATID }}' 