name: Continuous Integration, Test e Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request_review:
    types: [submitted] # <-- adiciona para capturar aprovação de PR também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
      
      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0

  telegram_failure_alert:
    needs: build
    runs-on: ubuntu-latest
    if: failure() 
    steps:
      - name: Send Telegram alert on failure
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚨 Atenção: A build do projeto ${{ github.repository }} falhou no commit ${{ github.sha }}. Veja detalhes: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  telegram_success_alert:
    needs: build
    runs-on: ubuntu-latest
    if: success() 
    steps:
      - name: Send Telegram alert on success
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🎉 Sucesso: A build do projeto ${{ github.repository }} foi concluída!\nCommit: ${{ github.sha }}\nVeja: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  telegram_pull_request_alert:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' 
    steps:
      - name: Send Telegram alert for Pull Request
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="📢 Novo Pull Request criado: ${{ github.event.pull_request.title }}\nAutor: ${{ github.event.pull_request.user.login }}\nLink: ${{ github.event.pull_request.html_url }}"

 
